---
all:
  children:
    pod1:
      children:
        routers:
          hosts:
            pod1r1:
              ansible_host: 172.16.1.1
              ansible_network_os: ios    
        core_switches:
          hosts:
            pod1sw1:
              ansible_host: 172.16.1.2
              ansible_network_os: eos
              ansible_become_method: enable
              ansible_become: true
            pod1sw2:
              ansible_host: 172.16.1.3
              ansible_network_os: eos
              ansible_become_method: enable
              ansible_become: true
        access_switches:
          hosts:
            pod1sw3:
              ansible_host: 172.16.1.4
              ansible_network_os: eos
              ansible_become_method: enable
              ansible_become: true